global with sharing class GroupAccountResponse {
    
    global String statusCode {get;set;}
    global String status {get;set;}
    global String message {get;set;}
    global String accountName {get;set;}
    global String groupMemberNumber {get;set;}
    global String groupType {get;set;}
    global String street {get;set;}
    global String city {get;set;}
    global String state {get;set;}
    global String zipCode {get;set;}
    global String country {get;set;}

    global GroupAccountResponse() {
        
    }
}